describe('Módulo Cadastros p2', () => {
    context('Cadastros p2', () => {
        require('../Crud/Cadastros/origens-oportunidade.spec')
        require('../Crud/Cadastros/paises.spec')
        require('../Crud/Cadastros/portes-empresa.spec')
        require('../Crud/Cadastros/prazos-pagamento.spec')
        require('../Crud/Cadastros/produtos.spec')
        require('../Crud/Cadastros/ramo-atividade.spec')
        require('../Crud/Cadastros/rating.spec')
        require('../Crud/Cadastros/regioes.spec')
        require('../Crud/Cadastros/resultado-abordagem.spec')
        require('../Crud/Cadastros/status-conta.spec')
        require('../Crud/Cadastros/status-evento.spec')
        require('../Crud/Cadastros/status-ocorrencia.spec')
        require('../Crud/Cadastros/subtipo-ocorrencia.spec')
        require('../Crud/Cadastros/subtipo-oportunidade.spec')
        require('../Crud/Cadastros/tabela-preco.spec')
        require('../Crud/Cadastros/tipos-acao.spec')
        require('../Crud/Cadastros/tipos-campanha.spec')
        require('../Crud/Cadastros/tipos-conta.spec')
        require('../Crud/Cadastros/tipos-contrato.spec')
        require('../Crud/Cadastros/tipos-defeito.spec')
        require('../Crud/Cadastros/tipos-documento.spec')
        require('../Crud/Cadastros/tipos-endereco.spec')
        require('../Crud/Cadastros/tipos-evento.spec')
        require('../Crud/Cadastros/tipos-follow.spec')
        // require('../Crud/Cadastros/tipos-oportunidade.spec')
        require('../Crud/Cadastros/tipos-pagamento.spec')
        require('../Crud/Cadastros/tipos-relacionamento.spec')
        require('../Crud/Cadastros/transportadora.spec')
        require('../Crud/Cadastros/unidade-medida.spec')
    })
})