describe('Módulo Cadastros', () => {
    context('Cadastros', () => {
        require('../Crud/Cadastros/area-interesse.spec')
        require('../Crud/Cadastros/caracteristicas.spec')
        require('../Crud/Cadastros/categorias-compromisso.spec')
        require('../Crud/Cadastros/categorias-despesa.spec')
        require('../Crud/Cadastros/categorias-produto.spec')
        require('../Crud/Cadastros/categorias-servico.spec')
        require('../Crud/Cadastros/categorias-tarefas.spec')
        require('../Crud/Cadastros/categorias-etapa-tarefas.spec')
        require('../Crud/Cadastros/cidades.spec')
        require('../Crud/Cadastros/concorrentes.spec')
        require('../Crud/Cadastros/criterios-avaliacao.spec')
        require('../Crud/Cadastros/departamentos.spec')
        require('../Crud/Cadastros/deposito.spec')
        require('../Crud/Cadastros/disposicoes-ocorrencias.spec')
        require('../Crud/Cadastros/enderecos.spec')
        require('../Crud/Cadastros/estados.spec')
        // require('../Crud/Cadastros/feriados.spec')
        require('../Crud/Cadastros/frases.spec')
        require('../Crud/Cadastros/funcoes.spec')
        require('../Crud/Cadastros/grupos-empresa.spec')
        require('../Crud/Cadastros/grupos-usuario.spec')
        require('../Crud/Cadastros/locais.spec')
        require('../Crud/Cadastros/modalidade-negocio.spec')
        require('../Crud/Cadastros/motivos-fechamento.spec')
        require('../Crud/Cadastros/motivos-inativacao.spec')
        require('../Crud/Cadastros/motivos-pausa.spec')
        require('../Crud/Cadastros/motivos-perda.spec')
        require('../Crud/Cadastros/origens-conta.spec')
        require('../Crud/Cadastros/origens-contato.spec')
        require('../Crud/Cadastros/origens-ocorrencia.spec')
    })
})